apiVersion: v1
kind: Service
metadata:
  name: tp-github-actions-mock-svc
  namespace: production
spec:
  selector:
    app: tp-github-actions-mock
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80